set-option -g history-limit 50000            # Increase scrollback buffer for long sessions
set -g mouse on                              # Enable mouse for resizing and scrolling
set -sg escape-time 10                       # Shorten escape time for Neovim
set-option -g focus-events on                # Allow terminal focus events

# Enable 256 colors for compatibility with modern applications
set -g default-terminal "tmux-256color"

# Copy Mode: Use Vim keys for navigation
setw -g mode-keys vi


# Set key bind to ctrl + a
unbind C-b
set-option -g prefix C-a
bind-key C-a send prefix


# Shortcut to reload configuration
bind R source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Shortcuts for pane management
bind-key - split-window -v                   # Vertical split
bind-key | split-window -h                   # Horizontal split
bind-key h select-pane -L                    # Move left
bind-key l select-pane -R                    # Move right
bind-key j select-pane -D                    # Move down
bind-key k select-pane -U                    # Move up
bind-key x kill-pane                         # Close pane

# Resize panes with arrow keys
bind -r Up resize-pane -U
bind -r Down resize-pane -D
bind -r Left resize-pane -L
bind -r Right resize-pane -R

# Window Management
set-option -g status-position top

# Plugins for added functionality (Optional: Requires TPM)
# List of plugins
set -g @plugin 'catppuccin/tmux#v2.1.2'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

set -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @plugin 'tmux-plugins/tmux-continuum'

# Advanced Scrolling (Use mouse and keyboard)
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Quick Navigation Shortcuts
bind -r Tab last-window                      # Toggle between last two windows
bind-key b previous-window                   # Go to the previous window
bind-key n next-window                       # Go to the next window
set -sg escape-time 10
set-option -g focus-events on
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'
run '~/.tmux/plugins/tpm/tpm'
